version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - app:/app
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  app:
