version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=raspberry.hinatan.jp,hinatan.jp
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=raspberry.hinatan.jp,hinatan.jp
      - LETSENCRYPT_EMAIL=k.kiyama117@gmail.com
    networks:
      - reverse-proxy
      - backend
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - reverse-proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - reverse-proxy

networks:
  backend:
  reverse-proxy:

volumes:
  certs:
  vhostd:
  html: