version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=raspberry.hinatan.jp,hinatan.jp,localhost
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=raspberry.hinatan.jp,hinatan.jp,localhost
      - LETSENCRYPT_EMAIL=k.kiyama117@gmail.com
      - DB_TYPE=postgres
    networks:
      - reverse-proxy
      - backend
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    restart: always
    networks:
      - reverse-proxy

networks:
  backend:
  reverse-proxy: