version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: raspberry.hinatan.jp
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: raspberry.hinatan.jp
      LETSENCRYPT_EMAIL: k.kiyama117@gmail.com
    networks:
      - backend
      - reverse-proxy
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    restart: always

networks:
  backend:
  reverse-proxy:
